### ISSUE TITLE
LivePage is disabling itself intermittently

### ISSUE THREAD

**Issue by Wittner** [MikeRogers0/LivePage#73] opened 2016-12-02 11:16 UTC
LivePage frequently disables itself while I'm working. Every few iterations it will lose its 'Live' badge and not update the browser when I make a change to a file.

Chrome version: Version 54.0.2840.98 (64-bit)
OS: iMac, late 2015 with Sierra 10.2
Editor: Atom

Let me know if you need any other info

**Comment by MikeRogers0** [comment] 2016-12-03 00:03
Oh that's not intended behaviour, do you have a link to the page/project you were working on (It'll help me debug)?

**Comment by MikeRogers0** [comment] 2017-01-08 03:36
#81 Might also fix this issue. I'll close this once I push 2.4.1 to production.

**Closed** 2017-01-08 03:51 UTC
Labels: Unable to reproduce

**Comment by Wittner** [comment] 2017-01-12 10:12
Sorry for the not gett back to you Mike. The app has not reproduced this behaviour in the last couple of weeks so it seems to have sorted itself. It's reporting version 2.4.2. and you were wondering if 2.4.1 would fix it. Looks like it did :-)
