### ISSUE TITLE
"file:// protocol needs enabling." - Enabled already

### ISSUE THREAD

**Issue by vincegio** [MikeRogers0/LivePage#91] opened 2017-01-25 12:30 UTC
> Sorry, the file:// protocol needs enabling. Please check the "Allow access to file URLs" for LivePage on the extensions page (chrome://extensions/).

It's enabled, but nothing. Restarted browser and toggled the extension.

**Comment by MikeRogers0** [comment] 2017-01-25 19:53
This is a duplicate of #86.

In this case, `chrome://` is the protocol & it's not supported. I'll update the copy to make it clearer.

**Closed by MikeRogers0** 2017-01-25 19:53 UTC
