### ISSUE TITLE
Bug: Options text can go missing 

### ISSUE THREAD

**Issue by chrisjj** [MikeRogers0/LivePage#85] opened 2017-01-09 01:40 UTC
Since clearing browing data http://i.imgur.com/J4OvTIi.png , whenever I click LP Options http://i.imgur.com/AdRyiVr.png I get lots of text missing:

![image](https://cloud.githubusercontent.com/assets/6157073/21755578/175e3448-d60e-11e6-86b1-e37976cf923b.png)

**Comment by MikeRogers0** [comment] 2017-01-09 02:01
Duplicate of #82 - A fix has been deployed & is currently rolling out to all users.

**Closed by MikeRogers0** 2017-01-09 02:01 UTC

**Comment by chrisjj** [comment] 2017-01-09 02:20
> Duplicate of #82

Ah, thanks. That had been closed, so I didn't see it.

Did this bug get delivered by an automatic update of my Live Page installation? If so, how can I disable automatic update?

**Comment by MikeRogers0** [comment] 2017-01-09 03:42
@chrisjj 
Extension automatic updates are managed by the chrome store.

To avoid automatic updates you can installed the [the development version of LivePage](https://github.com/mikerogers0/livepage#running-development-version-in-chrome), though this will display a warning every time you load chrome.

**Comment by chrisjj** [comment] 2017-01-09 12:00
> To avoid automatic updates you can install the the development version of LivePage, though this will display a warning every time you load chrome.

Thanks. That initially failed ("[x] Allow access to file URLs" http://i.imgur.com/TWT1I2s.png gave "Sorry this protocol is unsupported") but after browser restart, it works.

If I get tired of the warning, I'll try setting Read-Only on the production version's directory \Google Chrome\Data\profile\Default\Extensions\pilnojpmdoofaelbinaeodfpjheijkbh\2.4.1_0 hoping this won't prevent Options changes.
