### ISSUE TITLE
Getting request but page not reloading

### ISSUE THREAD

**Issue by Lorenzo45** [MikeRogers0/LivePage#44] opened 2016-05-19 21:00 UTC
My current stack is Heroku and Django with Sublime Text 2 and Chrome (OS X 10.11.2), and I can't seem to get my local pages to update. I can see the requests being made but the page doesn't reload.

**Comment by MikeRogers0** [comment] 2016-05-20 13:57
Possibly fixed in [2.0.0](https://github.com/MikeRogers0/LivePage/tree/2.0.0), which should be pushed out within the next hour.

If not, check the HTTP response your changed files are returning. If they are return 304 when they've changed, your stack is the cause of the errors (they should return a 200). As a work around, in the LivePage options check the option "Use only GET requests when polling for changes".

**Closed by MikeRogers0** 2016-05-20 13:57 UTC
