### ISSUE TITLE
chrome-extension:// is not a supported protocol

### ISSUE THREAD

**Issue by gkovacs** [MikeRogers0/LivePage#90] opened 2017-01-21 10:37 UTC
I'm trying to use this extension to develop the options page for a chrome extension of my own, which was side-loaded from the filesystem. However, when I click the LivePage icon while navigated to the options page URL (which has protocol chrome-extension:// ) it tells me that it is an unsupported protocol. Could you either add support for the chrome-extension:// protocol, or make it such that I can just specify the path to my extension's files and it'll reload that page whenever a file is edited?

**Comment by MikeRogers0** [comment] 2017-01-21 20:34
This is a duplicate of #69 - I'm working on making this option a power feature in the next release. I'm aiming to for an early February release :)

Also, best of luck on your extension!

**Closed by MikeRogers0** 2017-01-21 20:34 UTC
