### ISSUE TITLE
Uncaught TypeError In Console when using React

### ISSUE THREAD

**Issue by andyrichardson** [MikeRogers0/LivePage#46] opened 2016-06-11 20:16 UTC
`Uncaught TypeError: Cannot read property 'refresh_rate' of undefined`

I've encountered the following error which does not seem to effect functionality but is repeatedly posted in the console upon live page changes (although not consistently).

I think this has something to do with a need for 'mutual exclusion' during each call of `Settings.refresh()`\- the settings class might benefit from a more asynchronous approach.

**Comment by MikeRogers0** [comment] 2016-06-12 12:54
I can't reproduce this error, could you provide more information (the URL you're on and steps I can follow to see the error) to help me out?

**Comment by andyrichardson** [comment] 2016-06-12 13:19
URL: file:///home/andy/Development/React.js/index.html
Files: https://github.com/MyFrameworkSnippets/React.js

Reproduction:
Open html file in chrome, edit and save a linked javascript file (may take more than one attempt).

**Comment by MikeRogers0** [comment] 2016-06-19 12:30
I've had a chance to look into this error more closely this weekend, I wasn't able to reproduce the issue with the steps provided. Though I did also attempt to recreate the issue on a few react projects I have locally. 

I suspect that if your setup is anything like [this react tutorial](https://www.fullstackreact.com/articles/react-tutorial-cloning-yelp/), react is in development mode & is conflicting with LivePage. 

I'm going to leave this ticket open with an adjusted title incase any other users notice this problem & can provide more details.

**Comment by andyrichardson** [comment] 2016-06-23 11:36
That may very well be the case, I'll look into recreating this issue with/without using React and hopefully confirm your suspicions.

**Comment by MikeRogers0** [comment] 2016-06-23 14:40
Awesome thank you @andyrichardson !

**Comment by MikeRogers0** [comment] 2016-11-03 08:30
Hopefully fixed in https://github.com/MikeRogers0/LivePage/pull/65

**Closed by MikeRogers0** 2016-11-03 08:30 UTC
Labels: Unable to reproduce

**Comment by andyrichardson** [comment] 2016-11-03 14:55
Let me know if you want me to test it out.

**Comment by MikeRogers0** [comment] 2016-11-03 21:11
@andyrichardson That would be awesome if you could :)

**Comment by andyrichardson** [comment] 2016-11-06 15:33
All good here :+1:
